# -*- coding: utf-8 -*-
"""CRUD_operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C54SabYTWqlH-S1TL3kMNUKs5e8th5Jj
"""

import pymongo

data = pymongo.MongoClient("mongodb://vijay007:abcdefgh@cluster0-shard-00-00.hzbkh.mongodb.net:27017,cluster0-shard-00-01.hzbkh.mongodb.net:27017,cluster0-shard-00-02.hzbkh.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-s161q9-shard-0&authSource=admin&retryWrites=true&w=majority")

db = data["TELEPHONE_DIRECTORY"]

w = db["DIRECTORY"]

w.insert_one({"Name":"Kiran","Age":23,"Phone_number":9632154515,"Address":"delhi"})

w.insert_many([{"Name":"Karan","Age":23,"Phone_number":9632154678,"Address":"Banglore","State":"Karnataka"},{"Name":"Sharan","Age":26,"Phone_number":9632123478,"Address":"Banglore"},{"Name":"Kavya","Age":27,"Phone_number":7812452634,"Address":"Chennia"},{"Name":"Sindhu","Age":26,"Phone_number":7845128956,"Address":"Patna"},{"Name":"Samarth","Age":31,"Phone_number":7722772277,"Address":"Hubli"},{"Name":"Vidya","Age":24,"Phone_number":9756123789,"Address":"Banglore"},{"Name":"Karan","Age":28,"Phone_number":9632154678,"Address":"Banglore"}])

r = w.find()

for i in r:
  print(i)

a = w.update_one({"Name":"Kiran"},{"$set":{"Age":"30"}})

c = w.update_one({"Name":"Karan"},{"$unset":{"State":"Karnataka"}})

x = w.delete_one({"Name":"Kiran"})

