# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIGMwT1d33iY0dZJ_1DWC5R_7h_ItXe4
"""

import pandas as pd

import pymongo
from pymongo import MongoClient
uri = 'mongodb://vijay007:abcdefgh@cluster0-shard-00-00.hzbkh.mongodb.net:27017,cluster0-shard-00-01.hzbkh.mongodb.net:27017,cluster0-shard-00-02.hzbkh.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-s161q9-shard-0&authSource=admin&retryWrites=true&w=majority'
client = MongoClient(uri)

import pymongo
client = pymongo.MongoClient('mongodb://vijay007:abcdefgh@cluster0-shard-00-00.hzbkh.mongodb.net:27017,cluster0-shard-00-01.hzbkh.mongodb.net:27017,cluster0-shard-00-02.hzbkh.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-s161q9-shard-0&authSource=admin&retryWrites=true&w=majority')
db = client.student
stu = db.student
#1)Find the student name who scored maximum scores in all (exam, quiz and homework)?
def max_scorer(stu):
  x = stu.aggregate([{'$unwind':'$scores'},{'$group':{"_id":"$_id","name":{"$first":"$name"},"max_score":{'$sum':"$scores.score"}}}])
  max=0
  id=0
  for i in x:
    if i['max_score']>max:
      max=i['max_score']
      id=i['_id']
      name=i['name']
    else:
      pass
  print(name," is the max scorer with a total : ",max)


max_scorer(stu)

#2)Find students who scored below average in the exam and pass mark is 40%?
x2 = stu.find({"scores.type":'exam'})
for i in x2:
  s = [i["scores"]]
  name=[i['name']]
  for j in s:
    k=j[0]
    if k['score']>=40 and k['score']<=55:
      print(name,"--->",k['score'],":",k['type'])

def aggr(stu):
  prcntg = stu.aggregate([{'$unwind':'$scores'},
                           {'$group':{"_id":"$_id","name":{"$first":"$name"},"max_score":{'$sum':"$scores.score"}}},
                           {'$addFields':{"prctg":{'$divide':["$max_score",3]}}},
                            {'$addFields':{"status":{"$cond":{'if' :{"$gte":["$prctg",40]},'then':"Pass",'else':"Fail"}}}}])
  return prcntg

prcntg=aggr(stu)
for i in prcntg:
  if i['prctg']>=40 and i['prctg']<=55:
      print(i)

#3)Find students who scored below pass mark and assigned them as fail, and above pass mark as pass in all the categories.
prcntg=aggr(stu)
for i in prcntg:
  print(i)

#4)Find the total and average of the exam, quiz and homework and store them in a separate collection.
db.create_collection('total_average')
x2 = stu.aggregate([{'$unwind':'$scores'},{'$group':{'_id':{'type':"$scores.type"},"total:":{'$sum':"$scores.score"},"average:":{'$avg':"$scores.score"}}}])
t_a=db.total_average
for i in x2:
  print(i)
  t_a.insert_one(i)

#5)Create a new collection which consists of students who scored below average and above 40% in all the categories.
prcntg=aggr(stu)
db.create_collection('passed_below_average')   
p_a=db.passed_below_average
for i in prcntg:
  if i['prctg']>40 and i['prctg']<=55:
      print(i)
      p_a.insert_one(i)

#6)Create a new collection which consists of students who scored below the fail mark in all the categories.
prcntg=aggr(stu)
db.create_collection('failed')    
fail=db.failed
for i in prcntg:
  if i['status']=='Fail':
      print(i)
      fail.insert_one(i)

#7)Create a new collection which consists of students who scored above pass mark in all the categories.
prcntg=aggr(stu)
db.create_collection('passed') 
p=db.passed
for i in prcntg:
  if i['prctg']>=40:
      print(i)
      p.insert_one(i)